name: QA-Prod

on:
  workflow_dispatch:
  push:
    tags:
      - 'sandbox-[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set Docker Variables
      id: vars
      run: |
        REPOSITORY="sandbox-${GITHUB_REPOSITORY#*/}"
        echo "REPOSITORY=$REPOSITORY" >> $GITHUB_OUTPUT

        if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          RAW_TAG="${GITHUB_REF#refs/tags/}"         # e.g., sandbox-adminer-core:sandbox-1.1.3
          REPO_NAME="${RAW_TAG%%:*}"                 # e.g., sandbox-adminer-core
          VERSION_WITH_SANDBOX="${RAW_TAG#*:}"       # e.g., sandbox-1.1.3
          VERSION="${VERSION_WITH_SANDBOX#sandbox-}" # e.g., 1.1.3
          
          FINAL_TAG="${VERSION}"        # e.g., sandbox-adminer-core:1.1.3

          echo "TAG=$VERSION" >> $GITHUB_OUTPUT
          echo "DOCKER_TAG=$FINAL_TAG" >> $GITHUB_OUTPUT
          echo "TARGET=${{ secrets.SLACK_WEBHOOK_PROD }}" >> $GITHUB_OUTPUT
        else
          TAG="qa-${GITHUB_SHA::7}-$(date +%s)"
          FINAL_TAG="${TAG}"

          echo "TAG=$TAG" >> $GITHUB_OUTPUT
          echo "DOCKER_TAG=$FINAL_TAG" >> $GITHUB_OUTPUT
          echo "TARGET=${{ secrets.SLACK_WEBHOOK }}" >> $GITHUB_OUTPUT
        fi
    - name: Build the Docker image
      env:
        LLC_ECR_HOST: ${{ secrets.LLC_ECR_HOST }}
        TAG: ${{ steps.vars.outputs.DOCKER_TAG }}
        REPOSITORY: ${{ steps.vars.outputs.REPOSITORY }}
      run: |
        docker build . --file Dockerfile --tag ${LLC_ECR_HOST}/$REPOSITORY:$TAG
        docker push ${LLC_ECR_HOST}/$REPOSITORY:$TAG
    

    # - name: Build and Push Docker Image
    #   env:
    #     LLC_ECR_HOST: ${{ secrets.LLC_ECR_HOST }}
    #     DOCKER_TAG: ${{ steps.vars.outputs.DOCKER_TAG }}
    #   run: |
    #     IMAGE="${LLC_ECR_HOST}/${DOCKER_TAG}"
    #     echo "Building image: $IMAGE"
    #     docker build . --file Dockerfile --tag "$IMAGE"
    #     docker push "$IMAGE"
