name: QA-Prod

on:
  workflow_dispatch: # used for QA Deployments
  push:
    tags:
      - 'sandbox-*'
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set Docker Tag
      id: vars
      run: |
        REPOSITORY1="sandbox-${GITHUB_REPOSITORY#*/}"
        RAW_TAG="${GITHUB_REF#refs/tags/}"                         
        REPOSITORY="${RAW_TAG%%:*}"                                
        FULL_TAG="${RAW_TAG#*:}"                                   
        CLEAN_TAG="${FULL_TAG#sandbox-}"                           

        echo "REPOSITORY1=$REPOSITORY1"
        echo "CLEAN_TAG=$CLEAN_TAG"

        echo "REPOSITORY1=$REPOSITORY1" >> $GITHUB_ENV
        echo "TAG=$CLEAN_TAG" >> $GITHUB_ENV
        echo "TARGET=${{ secrets.SLACK_WEBHOOK_PROD }}" >> $GITHUB_ENV

        echo "::set-output name=REPOSITORY1::$REPOSITORY1"
        echo "::set-output name=TAG::$CLEAN_TAG"
        echo "::set-output name=TARGET::${{ secrets.SLACK_WEBHOOK_PROD }}"

    - name: Build and Push Docker Image
      env:
        LLC_ECR_HOST: ${{ secrets.LLC_ECR_HOST }}
        REPOSITORY: ${{ steps.vars.outputs.REPOSITORY1 }}
        TAG: ${{ env.TAG }}
      run: |
        IMAGE=${LLC_ECR_HOST}/${REPOSITORY}:${TAG}
        echo "Building Docker image: $IMAGE"
        docker build . --file Dockerfile --tag "$IMAGE"
        docker push "$IMAGE"
